apiVersion: v1
kind: Service
metadata:
  name: azure-front-svc
spec:
  # type: NodePort
  selector:
    app: azure-front-app
  ports:
    - port: 80
      targetPort: 4200
      # nodePort: 32002
      protocol: TCP
