apiVersion: v1
kind: Service
metadata:
  name: azure-back-svc
spec:
  # type: NodePort
  selector:
    app: azure-back-app
  ports:
    - port: 5000
      targetPort: 5000
      # nodePort: 5000
      protocol: TCP